# Generated by Django 2.2.7 on 2019-11-10 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('ticket_price', models.IntegerField(verbose_name='チケット値段')),
                ('guest_name', models.CharField(max_length=100, verbose_name='ゲスト名')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='招待者')),
            ],
            options={
                'verbose_name': '招待',
                'verbose_name_plural': '招待',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('had_visited', models.BooleanField(default=False, verbose_name='来訪')),
                ('visited_time', models.TimeField(null=True, verbose_name='来店時刻')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invite.Invite', verbose_name='招待')),
            ],
            options={
                'verbose_name': '参加確認ログ',
                'verbose_name_plural': '参加確認ログ',
                'ordering': ['-created'],
            },
        ),
    ]
